version: "3.2"
services:
  cockroachdb:
    container_name: cockroachdb
    image: cockroachdb/cockroach:latest
    volumes:
      - /data/cockroachdb:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"

  cockroach_init:
    image: cockroachdb/cockroach:latest
    depends_on:
      - cockroachdb
    volumes:
      - ./cockroach/:/home/
    entrypoint: /bin/bash
    command: /home/run_setup.sh